"""add health_status

Revision ID: 06a0c904ba0c
Revises: cc85db79b044
Create Date: 2024-05-10 13:39:57.085499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a0c904ba0c'
down_revision = 'cc85db79b044'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('host_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('current_day',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False, server_default="gewone burger"))
        batch_op.add_column(sa.Column('health_status', sa.String(), nullable=False, server_default="alive"))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('team',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default="burger team")
        batch_op.drop_column('rol')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('vote_from',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('day',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vote_type',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vote_to',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('vote_to',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('vote_type',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('day',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('vote_from',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('team',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('health_status')
        batch_op.drop_column('role')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('current_day',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('host_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
