"""add votes

Revision ID: 0c897007fcbb
Revises: 48bd6345ee87
Create Date: 2023-04-25 18:54:55.807984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c897007fcbb'
down_revision = '48bd6345ee87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
