"""add role and team

Revision ID: 2a39387c3c97
Revises: f4fa8ae6825f
Create Date: 2024-05-08 12:29:11.770371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a39387c3c97'
down_revision = 'f4fa8ae6825f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('rol', sa.String(), nullable=True))
    op.add_column('player', sa.Column('team', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'team')
    op.drop_column('player', 'rol')
    # ### end Alembic commands ###
