"""remove is_fake

Revision ID: 48bd6345ee87
Revises: 6309ca903a4e
Create Date: 2023-04-12 19:41:35.030503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48bd6345ee87'
down_revision = '6309ca903a4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'is_fake')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('is_fake', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
