"""add success and remove day from Info

Revision ID: 569a764d5489
Revises: fc9c46736989
Create Date: 2024-06-05 15:44:21.562786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '569a764d5489'
down_revision = 'fc9c46736989'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('success', sa.Boolean(), nullable=True))
        batch_op.alter_column('team_targets',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.drop_column('day')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.INTEGER(), nullable=True))
        batch_op.alter_column('team_targets',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.drop_column('success')

    # ### end Alembic commands ###
