"""add Info

Revision ID: 5b1de833e9a0
Revises: 06a0c904ba0c
Create Date: 2024-06-03 17:16:55.468201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1de833e9a0'
down_revision = '06a0c904ba0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('team_targets', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_info_id'), ['id'], unique=False)

    op.create_table('player_targets_info_table',
    sa.Column('info_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['info_id'], ['info.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['player.id'], )
    )
    op.create_table('team_targets_info_table',
    sa.Column('info_id', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['info_id'], ['info.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_targets_info_table')
    op.drop_table('player_targets_info_table')
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_info_id'))

    op.drop_table('info')
    # ### end Alembic commands ###
