"""added is_fake in Player

Revision ID: 6309ca903a4e
Revises: 1a4215753318
Create Date: 2023-03-26 20:15:07.852346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6309ca903a4e'
down_revision = '1a4215753318'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('is_fake', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_column('player', 'is_fake')
    # ### end Alembic commands ###
