"""add actions

Revision ID: 69b2679c4bea
Revises: 2a39387c3c97
Create Date: 2024-05-08 16:34:20.100848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b2679c4bea'
down_revision = '2a39387c3c97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_target_id', table_name='player_target')
    op.drop_table('player_target')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_target',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('action_id', sa.INTEGER(), nullable=True),
    sa.Column('target_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_target_id', 'player_target', ['id'], unique=False)
    # ### end Alembic commands ###
