"""replace info name with action id

Revision ID: fc9c46736989
Revises: 5b1de833e9a0
Create Date: 2024-06-03 22:09:21.819165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9c46736989'
down_revision = '5b1de833e9a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_id', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_foreign_key('fk_info_action_id_action', 'action', ['action_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('fk_info_action_id_action', type_='foreignkey')
        batch_op.drop_column('action_id')

    # ### end Alembic commands ###
